# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst

language: generic
dist: focal
services:
  - docker
notifications:
  email:
    recipients:
      - awckoenig@gmail.com
cache:
  directories:
    - $HOME/.ccache
env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="melodic"
    - ROS_DISTRO="noetic"
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh